version: '3.9'

services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    env_file:
      - ./backend/.env

  database:
    container_name: database-container
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  pgdata: